# Generated by Django 4.1.2 on 2022-10-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_alter_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
